### ISSUE TITLE
Dependencies of lambda functions with >0 args are not gathered

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/gather#21]
**Describe the bug**
UPDATE: After experimenting further it seems that program slicing fails specifically on a lambda function which accepts at least 1 argument.

**To Reproduce**

1. Build and run Gather extension.
2. Upload [this notebook](https://github.com/joyceerhl/jupyter-notebooks/blob/master/notebooks/Lambda%20functions.ipynb) to Jupyter.
3. Execute all cells.
4. Try gathering the definitions and outputs for each case.

**Expected Behavior**
Dependencies of lambda functions should be gathered.

**Screenshots**
![lambdas](https://user-images.githubusercontent.com/30305945/61192231-d3658980-a667-11e9-8796-d9649dc88163.gif)

**Comment by andrewhead** [comment]
Hey @joyceerhl! Thanks for pointing this out and the wonderful repro info. I found a small parsing inconsistency in the rules for parsing lambdas, which should be fixed in https://github.com/microsoft/gather/commit/60e050af4b3ccb403e68ebac3488eb8bf8f5564f

Want to try it out and see if works? Will require a `jlpm run build:parser` command to rebuild the parser. Here's what the fixed notebook looks like for me:
![image](https://user-images.githubusercontent.com/2358524/61513776-fb7c2200-a9b2-11e9-8c9a-a362be01ecad.png)

**Comment by joyceerhl** [comment]
Works great! Thanks @andrewhead :-)
